# Generated by GitHub Copilot on 2026-04-05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indie_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
